use super::*;

/// A scratch machine with one session of each kind: a Claude Code session (in `proj/demo`), a Codex session an
/// agent task ran, a Kimi session and an oriel chat. Returns the env and the Claude, Codex and chat file paths.
pub(crate) fn fixtures(name: &str) -> (Env, PathBuf, PathBuf, PathBuf) {
    let root = std::path::absolute(format!("target/test-scratch/search/{name}")).unwrap();
    let _ = std::fs::remove_dir_all(&root);
    let env = Env::under(&root);
    let demo = root.join("proj").join("demo");
    std::fs::create_dir_all(&demo).unwrap();
    let cwd = serde_json::to_string(&demo.to_string_lossy()).unwrap();
    let claude = env.paths.claude.join("projects").join("proj-demo").join("sess-1.jsonl");
    std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
    let lines = [
        r#"{"type":"summary","summary":"Flaky login test fix","leafUuid":"x"}"#.to_string(),
        format!(r#"{{"type":"user","sessionId":"sess-1","cwd":{cwd},"timestamp":"2026-09-20T10:00:00.000Z","message":{{"role":"user","content":"the login test is flaky <private>my token is hunter2</private> please fix it"}}}}"#),
        format!(r#"{{"type":"user","isMeta":true,"sessionId":"sess-1","cwd":{cwd},"timestamp":"2026-09-20T10:00:01.000Z","message":{{"role":"user","content":"Caveat: The messages below were generated by the user while running local commands."}}}}"#),
        format!(r#"{{"type":"assistant","sessionId":"sess-1","cwd":{cwd},"timestamp":"2026-09-20T10:00:05.000Z","message":{{"role":"assistant","content":[{{"type":"text","text":"The clock mocking races with the retry loop."}},{{"type":"tool_use","id":"tu1","name":"Bash","input":{{"command":"cargo test login"}}}}]}}}}"#),
        r#"{"type":"user","sessionId":"sess-1","timestamp":"2026-09-20T10:00:09.000Z","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"tu1","is_error":true,"content":"error: test login_retries failed: timeout"}]}}"#.to_string(),
        r#"{"type":"assistant","sessionId":"sess-1","timestamp":"2026-09-20T10:00:12.000Z","message":{"role":"assistant","content":[{"type":"tool_use","id":"tu2","name":"TodoWrite","input":{"todos":[]}},{"type":"text","text":"We decided to replace sleep with a fake clock."}]}}"#.to_string(),
        r#"{"type":"user","sessionId":"sess-1","timestamp":"2026-09-20T10:01:00.000Z","message":{"role":"user","content":"<system-reminder>ignore me</system-reminder>great, thanks"}}"#.to_string(),
    ];
    std::fs::write(&claude, lines.join("\n") + "\n").unwrap();
    // a subagent's transcript isn't a session of its own
    let sub = claude.with_extension("").join("subagents").join("agent-a.jsonl");
    std::fs::create_dir_all(sub.parent().unwrap()).unwrap();
    std::fs::write(&sub, r#"{"type":"user","sessionId":"sess-1","message":{"role":"user","content":"subagent chatter"}}"#.to_string() + "\n").unwrap();

    let codex = env.paths.codex.join("sessions").join("2026").join("09").join("18").join("rollout-2026-09-18T08-00-00-th42.jsonl");
    std::fs::create_dir_all(codex.parent().unwrap()).unwrap();
    let lines = [
        r#"{"timestamp":"2026-09-18T08:00:00.000Z","type":"session_meta","payload":{"id":"th-42","timestamp":"2026-09-18T08:00:00.000Z","cwd":"/home/you/api"}}"#,
        r#"{"timestamp":"2026-09-18T08:00:01.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"<environment_context>\n  <cwd>/home/you/api</cwd>\n</environment_context>"}]}}"#,
        r#"{"timestamp":"2026-09-18T08:00:02.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"add rate limiting to the upload endpoint"}]}}"#,
        r#"{"timestamp":"2026-09-18T08:00:03.000Z","type":"event_msg","payload":{"type":"user_message","message":"add rate limiting to the upload endpoint"}}"#,
        r#"{"timestamp":"2026-09-18T08:00:04.000Z","type":"response_item","payload":{"type":"function_call","name":"shell","arguments":"{\"command\":[\"bash\",\"-lc\",\"rg upload src\"]}","call_id":"c1"}}"#,
        r#"{"timestamp":"2026-09-18T08:00:09.000Z","type":"response_item","payload":{"type":"message","role":"assistant","content":[{"type":"output_text","text":"Added a token bucket in the upload handler."}]}}"#,
    ];
    std::fs::write(&codex, lines.join("\n") + "\n").unwrap();

    let kimi = env.paths.home.join(".kimi-code").join("sessions").join("wd_tools_1234").join("session_9").join("agents").join("main").join("wire.jsonl");
    std::fs::create_dir_all(kimi.parent().unwrap()).unwrap();
    std::fs::write(&kimi, "{\"timestamp\": 1758355200, \"message\": {\"role\": \"user\", \"content\": \"rename the kimi config loader\"}}\n{\"timestamp\": 1758355210, \"message\": {\"role\": \"assistant\", \"content\": [{\"type\":\"text\",\"text\":\"Renamed it to load_settings.\"}]}}\n").unwrap();

    let chat = env.chats.join("c1.json");
    std::fs::create_dir_all(&env.chats).unwrap();
    let c = serde_json::json!({"id": "c1", "title": "plan a trip", "created": 1758000000.0, "updated": 1758000100.0, "provider": "claude", "cwd": demo.to_string_lossy(),
        "messages": [{"role": "user", "content": "plan a 3 day trip to lisbon"},
            {"role": "assistant", "content": "Day 1: Alfama", "parts": [{"kind": "text", "text": "Day 1: Alfama"},
                {"kind": "tool", "id": "t1", "name": "WebSearch", "label": "Web search", "target": "lisbon trams", "status": "done"}]}]});
    std::fs::write(&chat, c.to_string()).unwrap();

    std::fs::create_dir_all(env.tasks.parent().unwrap()).unwrap();
    std::fs::write(&env.tasks, serde_json::json!({"tasks": [{"id": "k1", "title": "fix upload limits", "transcript_path": codex.to_string_lossy()}]}).to_string()).unwrap();
    (env, claude, codex, chat)
}

fn kinds(d: &extract::Doc) -> Vec<(Kind, String)> {
    d.turns.iter().map(|t| (t.kind, t.text.clone())).collect()
}

#[test]
fn recall_extracts_each_format() {
    let (env, claude, codex, chat) = fixtures("extract");
    let d = extract::claude(&claude).unwrap();
    assert_eq!(d.title, "Flaky login test fix");
    assert_eq!(d.session, "sess-1");
    assert!(d.cwd.ends_with("demo"), "{}", d.cwd);
    assert_eq!(
        kinds(&d),
        vec![
            (Kind::You, "the login test is flaky please fix it".to_string()),
            (Kind::Ai, "The clock mocking races with the retry loop.".to_string()),
            (Kind::Tool, "Bash\tcargo test login\nerror: test login_retries failed: timeout".to_string()),
            (Kind::Ai, "We decided to replace sleep with a fake clock.".to_string()),
            (Kind::You, "great, thanks".to_string()),
        ],
        "private span, the meta caveat, the reminder and the todo plumbing are all left out"
    );
    assert!(d.started > 0 && d.updated > d.started);

    let d = extract::codex(&codex).unwrap();
    assert_eq!((d.session.as_str(), d.cwd.as_str()), ("th-42", "/home/you/api"));
    assert_eq!(
        kinds(&d),
        vec![
            (Kind::You, "add rate limiting to the upload endpoint".to_string()),
            (Kind::Tool, "Bash\trg upload src".to_string()),
            (Kind::Ai, "Added a token bucket in the upload handler.".to_string()),
        ],
        "the environment block isn't something you typed, and event_msg repeats aren't doubled"
    );
    assert_eq!(d.title, "add rate limiting to the upload endpoint");

    let kimi = usage::discover(&env.paths).into_iter().find(|(s, _)| *s == usage::Src::Kimi).unwrap().1;
    let d = extract::generic(&kimi).unwrap();
    assert_eq!(d.turns.len(), 2);
    assert_eq!(d.session, "session_9");
    assert_eq!(d.turns[1].text, "Renamed it to load_settings.");

    let d = extract::oriel(&chat).unwrap();
    assert_eq!(d.title, "plan a trip");
    assert_eq!(kinds(&d)[2], (Kind::Tool, "Web search\tlisbon trams".to_string()));

    // the file round-trips, and text that looks like a marker can't break it
    let turns = vec![Turn { kind: Kind::You, t: 5, text: "@@ -1,3 +1,4 @@\nline".into() }, Turn { kind: Kind::Tool, t: 0, text: "Bash\tls".into() }];
    assert_eq!(extract::parse(&extract::write(&turns)), turns);
    assert_eq!(extract::clean("a <private>x</private>b <PRIVATE>y"), "a b");
    assert_eq!(extract::clean("a <private>x</private> b"), "a b");
    assert_eq!(extract::clean("run <command-name>/review</command-name><command-args>pr 7</command-args>"), "run /review pr 7");
}

#[test]
fn recall_index_updates_and_archives() {
    let (env, claude, codex, chat) = fixtures("update");
    // a session quit before its first prompt: nothing to find, and not read again until it changes
    let empty = claude.with_file_name("sess-empty.jsonl");
    std::fs::write(&empty, "{\"type\":\"file-history-snapshot\",\"messageId\":\"m1\",\"snapshot\":{}}\n").unwrap();
    let (m, st) = update(&env, 2, &|_, _| {});
    assert_eq!(m.sessions.len(), 4, "{:#?}", m.sessions);
    assert_eq!(st.changed, 5);
    assert_eq!(m.empty.len(), 1, "{:?}", m.empty);
    // (sess-2 turns up below)
    let by = |m: &Manifest, src: Src| m.sessions.iter().find(|e| e.src == src && e.session != "sess-2").cloned().unwrap();
    let c = by(&m, Src::Claude);
    assert_eq!((c.session.as_str(), c.project.as_str(), c.turns), ("sess-1", "demo", 2));
    assert!(env.extract_file(&c.id).is_file());
    let x = by(&m, Src::Codex);
    assert_eq!((x.task.as_str(), x.title.as_str(), x.who()), ("fix upload limits", "fix upload limits", "agent"), "the agents app ran it");
    assert_eq!(by(&m, Src::Kimi).project, "", "no folder in that format");
    assert_eq!(m.sessions[0].src, Src::Claude, "newest first");
    let (per, agents, gone) = m.counts();
    assert_eq!((per.len(), agents, gone), (4, 1, 0));

    // nothing changed: nothing is read again (the empty one included)
    let (m, st) = update(&env, 2, &|_, _| {});
    assert_eq!((st.changed, st.files, m.empty.len()), (0, 5, 1));
    // a session that grew is
    let mut f = std::fs::OpenOptions::new().append(true).open(&claude).unwrap();
    use std::io::Write;
    writeln!(f, r#"{{"type":"user","sessionId":"sess-1","timestamp":"2026-09-21T09:00:00.000Z","message":{{"role":"user","content":"one more thing about the retry loop"}}}}"#).unwrap();
    drop(f);
    let (m, st) = update(&env, 2, &|_, _| {});
    assert_eq!(st.changed, 1);
    assert_eq!(by(&m, Src::Claude).turns, 3);
    assert_eq!(m.sessions.len(), 4, "read again, not listed twice");
    // so does the empty one, once it has a prompt in it
    std::fs::write(&empty, r#"{"type":"user","sessionId":"sess-2","timestamp":"2026-09-22T09:00:00.000Z","message":{"role":"user","content":"now it has words"}}"#.to_string() + "\n").unwrap();
    let (m, st) = update(&env, 2, &|_, _| {});
    assert_eq!((st.changed, m.sessions.len(), m.empty.len()), (1, 5, 0));

    // the agents app records later that one of its tasks ran the Claude session: it's an agent run now
    std::fs::write(&env.tasks, serde_json::json!({"tasks": [{"id": "k1", "title": "fix upload limits", "transcript_path": codex.to_string_lossy()},
        {"id": "k2", "title": "stabilise the login test", "transcript_path": claude.to_string_lossy()}]}).to_string()).unwrap();
    let (m, st) = update(&env, 2, &|_, _| {});
    let c = by(&m, Src::Claude);
    assert_eq!((st.changed, c.title.as_str(), c.who()), (0, "stabilise the login test", "agent"), "without reading it again");

    // Claude Code cleaned the session up: the extract is the archive now
    std::fs::remove_file(&claude).unwrap();
    std::fs::remove_file(&chat).unwrap();
    let (m, _) = update(&env, 2, &|_, _| {});
    let c = by(&m, Src::Claude);
    assert!(c.gone && env.extract_file(&c.id).is_file(), "kept, marked archived");
    assert!(!m.sessions.iter().any(|e| e.src == Src::Oriel), "a chat you deleted is gone from search too");
    let hits = search(&env, &m, &Query::parse("fake clock"), now(), 10, 2);
    assert_eq!(hits.len(), 1, "an archived session is still found");
    let _ = codex;
}

fn now() -> i64 {
    crate::panes::files::clock::now_secs()
}

#[test]
fn recall_search_filters_and_snippets() {
    let (env, ..) = fixtures("query");
    let (m, _) = update(&env, 2, &|_, _| {});
    let q = |s: &str| search(&env, &m, &Query::parse(s), now(), 50, 2);

    let hits = q("fake clock");
    assert_eq!(hits.len(), 1);
    let h = &hits[0];
    assert_eq!(h.entry.src, Src::Claude);
    assert_eq!(h.kind, Kind::Ai);
    assert_eq!(h.msg, 1, "the reply after the first prompt");
    assert_eq!(h.snippet[0], "We decided to replace sleep with a fake clock.");
    assert!(q("hunter2").is_empty(), "<private> is never indexed");
    assert!(q("subagent chatter").is_empty(), "subagent transcripts aren't sessions");
    assert_eq!(q("\"token bucket\"")[0].entry.src, Src::Codex, "a quoted phrase");
    assert!(q("\"bucket token\"").is_empty());
    // a failed call's error is findable, and shown as the tool line
    let h = &q("login_retries")[0];
    assert_eq!(h.kind, Kind::Tool);
    assert!(h.snippet.iter().any(|s| s.contains("login_retries")), "{:?}", h.snippet);
    // title words count
    assert_eq!(q("trip")[0].entry.src, Src::Oriel);

    // filters
    assert_eq!(q("upload ai:agent").len(), 1);
    assert!(q("upload ai:claude").is_empty());
    assert_eq!(q("ai:kimi").len(), 1);
    let demo: Vec<Src> = q("p:demo").iter().map(|h| h.entry.src).collect();
    assert_eq!(demo, vec![Src::Claude, Src::Oriel], "no words: newest first, only that project");
    assert_eq!(q("p:demo")[0].snippet[0], "the login test is flaky please fix it", "no words: the first prompt");
    let far = 4_000_000_000;
    assert!(search(&env, &m, &Query::parse("since:30d"), far, 50, 2).is_empty());
    assert_eq!(search(&env, &m, &Query::parse("since:100y"), far, 50, 2).len(), 4);

    let p = Query::parse("  Retry \"fake Clock\" p:Demo ai:cc since:2w ai:nope since:soon ");
    assert_eq!(p.terms, vec!["retry", "fake clock"]);
    assert_eq!((p.project.as_deref(), p.ai.as_deref(), p.since), (Some("demo"), Some("claude"), Some(14 * 86400)));
    assert_eq!(p.bad, vec!["ai:nope", "since:soon"]);
}

#[test]
fn recall_excerpt_and_messages() {
    let (env, ..) = fixtures("excerpt");
    let (m, _) = update(&env, 2, &|_, _| {});
    let e = m.sessions.iter().find(|e| e.src == Src::Claude).unwrap();
    let turns = load(&env, e);
    let msgs = messages(&turns);
    assert_eq!(msgs.len(), 3, "prompt · reply with its tool call · prompt");
    assert_eq!(msgs[1].len(), 3);
    let x = excerpt(e, &turns, 1, now());
    assert!(x.starts_with("(from a claude code session in demo, "), "{x}");
    assert!(x.contains("\"Flaky login test fix\")"), "{x}");
    assert!(x.contains("you: the login test is flaky"), "{x}");
    assert!(x.contains("claude code: The clock mocking races with the retry loop.\n[Bash cargo test login]\nWe decided"), "{x}");
    assert!(x.contains("you: great, thanks"), "{x}");
    assert_eq!(when(0, now()), "undated");
    assert!(when(now(), now()).starts_with("today "));
}

/// How long a query takes over a big index (3000 sessions, ~120 MB of text):
/// `cargo test recall_speed -- --ignored --nocapture`
#[test]
#[ignore]
fn recall_speed() {
    let root = std::path::absolute("target/test-scratch/search/speed").unwrap();
    let env = Env::under(&root);
    std::fs::create_dir_all(&env.index).unwrap();
    const WORDS: &[&str] = &["the", "retry", "loop", "parser", "upload", "token", "bucket", "fix", "test", "build", "cargo", "render", "pane", "chat", "index", "clock", "sleep", "merge", "branch", "config"];
    let mut seed = 7u64;
    let mut m = Manifest { v: VERSION, ..Default::default() };
    for i in 0..3000 {
        let mut text = String::new();
        for turn in 0..40 {
            text.push_str(if turn % 2 == 0 { "\u{1e}you 0\n" } else { "\u{1e}ai 0\n" });
            for _ in 0..160 {
                seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                text.push_str(WORDS[(seed >> 33) as usize % WORDS.len()]);
                text.push(' ');
            }
            text.push('\n');
        }
        if i == 1234 {
            text.push_str("\u{1e}ai 0\nwe decided to use a fake clock\n");
        }
        let id = format!("{i:016x}");
        std::fs::write(env.extract_file(&id), &text).unwrap();
        m.sessions.push(Entry { id, src: Src::Claude, title: format!("session {i}"), updated: i as i64, ..Default::default() });
    }
    let bytes: u64 = m.sessions.iter().map(|e| std::fs::metadata(env.extract_file(&e.id)).unwrap().len()).sum();
    for (q, threads) in [("fake clock", 8), ("fake clock", 8), ("retry loop", 8), ("\"fake clock\"", 1)] {
        let t0 = Instant::now();
        let hits = search(&env, &m, &Query::parse(q), 0, 200, threads);
        println!("{q:<14} {threads} threads: {} hits in {} ms over {} sessions, {} MB", hits.len(), t0.elapsed().as_millis(), m.sessions.len(), bytes >> 20);
    }
}

/// Index this computer's real sessions into a folder of your choosing and time it. Reads ~/.claude, ~/.codex,
/// ~/.kimi-code and oriel's chats, writes only to that folder, prints only counts and timings:
/// `ORIEL_RECALL_SCRATCH=<folder> cargo test recall_real_machine -- --ignored --nocapture`
#[test]
#[ignore]
fn recall_real_machine() {
    let dir = PathBuf::from(std::env::var("ORIEL_RECALL_SCRATCH").expect("set ORIEL_RECALL_SCRATCH"));
    let mut env = Env::real();
    env.index = dir.join("index");
    let (m, st) = update(&env, 8, &|_, _| {});
    let (per, agents, gone) = m.counts();
    let bytes: u64 = m.sessions.iter().filter_map(|e| std::fs::metadata(env.extract_file(&e.id)).ok()).map(|x| x.len()).sum();
    let src_bytes: u64 = m.sessions.iter().map(|e| e.size).sum();
    println!("first pass: {} sessions {per:?} · {agents} agent runs · {gone} archived · {} files, read {} in {} ms", m.sessions.len(), st.files, st.changed, st.ms);
    println!("extracts: {} MB of text from {} MB of transcripts", bytes >> 20, src_bytes >> 20);
    let empty_titles = m.sessions.iter().filter(|e| e.title.is_empty()).count();
    let no_project = m.sessions.iter().filter(|e| e.project.is_empty() && e.src != Src::Kimi).count();
    println!("untitled: {empty_titles} · without a project: {no_project}");
    let (_, st) = update(&env, 8, &|_, _| {});
    println!("second pass: {} files, read {} in {} ms", st.files, st.changed, st.ms);
    for q in ["test", "fix the bug", "cargo build", "\"merge conflict\"", "since:7d", "error ai:codex"] {
        let t0 = Instant::now();
        let hits = search(&env, &m, &Query::parse(q), now(), 200, 8);
        println!("{q:<20} {:>4} hits in {} ms", hits.len(), t0.elapsed().as_millis());
    }
}
